services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./services/user/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - core-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  user_service:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "${SERVER_HTTP_PORT}:8080"
    env_file:
      - ./services/user/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - core-net
    command: ["/wait_for_postgres.sh", "./app"]
    volumes:
      - ./services/user/keys:/keys

  robokassa_service:
    build:
      context: ./services/robokassa
      dockerfile: Dockerfile
    container_name: robokassa_service
    ports:
      - "8082:8082"
    env_file:
      - ./services/robokassa/.env
    depends_on:
      - postgres
    networks:
      - core-net
    command: ["/wait_for_postgres.sh", "./mock"]

  goose:
    build: ./services/user/tools/goose
    container_name: goose
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services/user/migrations:/migrations
    entrypoint: ["/goose/entrypoint.sh"]
    env_file:
      - ./services/user/.env
    networks:
      - core-net

  goose_robokassa:
    build: ./services/robokassa/tools/goose
    container_name: goose_robokassa
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services/robokassa/migrations:/migrations
    entrypoint: [ "/goose/entrypoint.sh" ]
    env_file:
      - ./services/robokassa/.env
    networks:
      - core-net

volumes:
  postgres_data:

networks:
  core-net:
    external: true
